In [8]:
import numpy as np
import pandas as pd
import scipy.stats as stats
from scipy.stats import ttest_1samp
import math

In [9]:

ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [10]:
ages

[10,
 20,
 35,
 50,
 28,
 40,
 55,
 18,
 16,
 55,
 30,
 25,
 43,
 18,
 30,
 28,
 14,
 24,
 16,
 17,
 32,
 35,
 26,
 27,
 65,
 18,
 43,
 23,
 21,
 20,
 19,
 70]

In [11]:
len(ages)

32

In [12]:
ages_mean = np.mean(ages)
print(ages_mean)

30.34375


In [13]:
# One sample T-test
sample_size = 10
ages_sample = np.random.choice(ages, sample_size)

In [14]:
ages_sample

array([18, 10, 16, 18, 24, 16, 14, 20, 35, 20])

In [15]:
ttest, p_value = ttest_1samp(ages_sample, 30)

In [16]:
ttest

np.float64(-5.1137465249700655)

In [17]:
p_value

np.float64(0.0006332948435352452)

In [18]:
if p_value < 0.05:    
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


In [20]:
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)


In [21]:
classA_ages.mean()

np.float64(46.9)

In [ ]:
_,p_value=stats.ttest_1samp(a=classA_ages,popmean=school_ages.mean())

In [23]:
p_value

np.float64(1.139027071016194e-13)

In [24]:
if p_value < 0.05:    
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


In [ ]:
# Two sample T test
np.random.seed(12)
classB_ages = stats.poisson.rvs(loc=18, mu=33, size=60)
classB_ages.mean()

np.float64(50.63333333333333)

In [29]:
_, p_value = stats.ttest_ind(a=classA_ages, b=classB_ages, equal_var=False)
p_value

np.float64(0.00039942095100859375)

In [30]:
if p_value < 0.05:    
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


In [31]:
# Paired T test
weight1=[25,30,28,35,28,34,26,29,30,26,28,32,31,30,45]
weight2=weight1+stats.norm.rvs(scale=5,loc=-1.25,size=15)

In [32]:
weight_df=pd.DataFrame({"weight_10":np.array(weight1),
                         "weight_20":np.array(weight2),
                       "weight_change":np.array(weight2)-np.array(weight1)})

In [33]:
_,p_value=stats.ttest_rel(a=weight1,b=weight2)

In [34]:
p_value

np.float64(0.5732936534411279)

In [35]:
if p_value < 0.05:    
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


In [3]:
# Chi Square Test
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np

In [4]:
dataset=sns.load_dataset('tips')

In [5]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
dataset_table = pd.crosstab(dataset['sex'], dataset['smoker'])

In [7]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [9]:
dataset_table.values

array([[60, 97],
       [33, 54]])

In [10]:
observed_values = dataset_table.values
print(observed_values)

[[60 97]
 [33 54]]


In [11]:
val = stats.chi2_contingency(dataset_table)
print(val)

Chi2ContingencyResult(statistic=np.float64(0.0), pvalue=np.float64(1.0), dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))


In [12]:
val

Chi2ContingencyResult(statistic=np.float64(0.0), pvalue=np.float64(1.0), dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))

In [15]:
expected_values = val[3]

In [16]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [17]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [19]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [20]:
chi_square_statistic

np.float64(0.001934818536627623)

In [21]:
critical_value = chi2.ppf(q=1-alpha, df=ddof)

In [22]:
critical_value

np.float64(3.841458820694124)

In [ ]:
p_value = 1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.964915107315732
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.964915107315732


In [24]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
Retain H0,There is no relationship between 2 categorical variables
